name: CyberSecurity_Awareness_Bot

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    runs-on: windows-latest
    
    env:
      Solution_Name: CyberSecurity_Awareness_Bot.sln
      Test_Project_Path: CyberSecurity_Awareness_Bot.Tests\CyberSecurity_Awareness_Bot.Tests.csproj
      Wap_Project_Directory: CyberSecurity_Awareness_Bot.Package
      Wap_Project_Path: CyberSecurity_Awareness_Bot.Package\CyberSecurity_Awareness_Bot.Package.wapproj

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore Dependencies
      run: dotnet restore

    - name: Execute Unit Tests
      run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Restore the Application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Decode the Signing Certificate
      run: |
        $certificatePath = "$env:Wap_Project_Directory\GitHubActionsWorkflow.pfx"
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - name: Create the App Package
      run: msbuild $env:Wap_Project_Path /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=StoreUpload /p:AppxBundle=Always /p:AppxBundlePlatforms="x86|x64" /p:PackageCertificateKeyFile="$env:Wap_Project_Directory\GitHubActionsWorkflow.pfx" /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Remove the Signing Certificate
      run: Remove-Item -Path "$env:Wap_Project_Directory\GitHubActionsWorkflow.pfx"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
